const jobData = [
    {
      jobName: 'Front-End Developer',
      jobType: 'Fulltime',
      jobID: '122345',
      location: 'New York, NY',
      experience: '1-3',
      companyOverview: 'Company ABC is a leading tech company specializing in web development and design services.',
      roleAndResponsibilities: [
        'Design and implement user interfaces for web applications.',
        'Collaborate with cross-functional teams to deliver high-quality front-end solutions.',
        'Optimize web applications for maximum speed and scalability.',
      ],
      candidateQualifications: [
        'Bachelor’s degree in Computer Science or related field.',
        'Proven experience in front-end development.',
        'Strong problem-solving and communication skills.',
      ],
      requiredSkills: ['React', 'JavaScript', 'CSS', 'Responsive Design', 'HTML', 'Version Control (e.g., Git)', 'UI/UX Design Principles'],
      workplaceType: 'On-site',
      annualCTC: '₹80,000 - ₹100,000',
      skills: 'Communication, Problem-Solving, Creativity',
    },
    {
      jobName: 'Back-End Developer',
      jobType: 'Part-time',
      jobID: '122346',
      location: 'San Francisco, CA',
      experience: '2-5',
      companyOverview: 'Company XYZ is a software development company specializing in backend solutions for various industries.',
      roleAndResponsibilities: [
        'Develop server-side logic and APIs for web applications.',
        'Work on database design and optimization.',
        'Collaborate with the front-end team to ensure seamless integration.',
      ],
      candidateQualifications: [
        'Bachelor’s degree in Computer Science or related field.',
        'Experience in back-end development with Node.js.',
        'Strong problem-solving and analytical skills.',
      ],
      requiredSkills: ['Node.js', 'SQL', 'RESTful APIs', 'Database Management', 'Version Control (e.g., Git)'],
      workplaceType: 'Remote',
      annualCTC: '₹60,000 - ₹80,000',
      skills: 'Problem-Solving, Collaboration, Adaptability',
    },
    {
      jobName: 'UX Designer',
      jobType: 'Internship',
      jobID: '122347',
      location: 'Los Angeles, CA',
      experience: '0',
      companyOverview: 'Company LMN is a design studio focused on creating user-centered and visually appealing digital experiences.',
      roleAndResponsibilities: [
        'Create wireframes, prototypes, and user interface designs.',
        'Collaborate with the product team to improve the user experience.',
        'Conduct user research and usability testing.',
      ],
      candidateQualifications: [
        'Pursuing or recently completed a degree in User Experience (UX) or related field.',
        'Strong passion for user-centered design and creativity.',
      ],
      requiredSkills: ['UI/UX Design Tools (e.g., Figma, Sketch)', 'User Research', 'Prototyping', 'Problem-Solving'],
      workplaceType: 'In-Person',
      annualCTC: 'Unpaid (Internship)',
      skills: 'Creativity, Attention to Detail, User-Centered Design',
    },
    {
      jobName: 'Product Manager',
      jobType: 'Freelance',
      jobID: '122348',
      location: 'Chicago, IL',
      experience: '1-4',
      companyOverview: 'Company OPQ is a startup working on innovative software products for businesses of all sizes.',
      roleAndResponsibilities: [
        'Define product goals, requirements, and roadmaps.',
        'Collaborate with development teams to deliver product features.',
        'Conduct market research and competitor analysis.',
      ],
      candidateQualifications: [
        'Bachelor’s degree in Business, Marketing, or related field.',
        'Experience in product management or related roles.',
        'Excellent communication and leadership skills.',
      ],
      requiredSkills: ['Product Management', 'Market Research', 'Agile Methodologies', 'Communication', 'Problem-Solving'],
      workplaceType: 'Remote (Freelance)',
      annualCTC: '₹70,000 - ₹90,000',
      skills: 'Leadership, Communication, Strategic Thinking',
    },
    {
      jobName: 'Data Scientist',
      jobType: 'Fulltime',
      jobID: '122349',
      location: 'Seattle, WA',
      experience: '0-6',
      companyOverview: 'Company XYZ is a data-driven technology company specializing in data analytics and machine learning solutions.',
      roleAndResponsibilities: [
        'Analyze large datasets to extract valuable insights.',
        'Build predictive models and machine learning algorithms.',
        'Collaborate with data engineers to ensure data quality.',
      ],
      candidateQualifications: [
        'Master’s or Ph.D. in Data Science, Computer Science, or related field.',
        'Experience in data analysis and machine learning.',
        'Strong programming skills in Python or R.',
      ],
      requiredSkills: ['Data Analysis', 'Machine Learning', 'Python', 'Statistics', 'Data Visualization'],
      workplaceType: 'On-site',
      annualCTC: '₹90,000 - ₹120,000',
      skills: 'Data Analysis, Machine Learning, Statistical Modeling',
    },
  ];

  export default jobData;